import { useCallback, useEffect, useState } from "react"
import { GitBranch, RefreshCw, Search } from "lucide-react"
import { getRealityMemory, type RealityMemory } from "../lib/api"

export default function MemoryLedger() {
  const [memories, setMemories] = useState<RealityMemory[]>([])
  const [query, setQuery] = useState("")
  const [loading, setLoading] = useState(true)
  const load = useCallback(async (term = query) => { setLoading(true); try { const data = await getRealityMemory(term, true); setMemories(data.memories) } finally { setLoading(false) } }, [query])
  useEffect(() => { void load("") }, [load])
  return <div className="mx-auto max-w-5xl"><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2f5eeb]">Technical proof</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Reality Memory Ledger</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#637080]">Every claim keeps its source lineage and time state. Conflicting evidence supersedes a claim; it never silently overwrites it.</p><form onSubmit={(event) => { event.preventDefault(); void load() }} className="mt-6 flex gap-2"><div className="flex flex-1 items-center gap-2 rounded-xl border border-[#d9d3c8] bg-[#fffcf7] px-3"><Search className="h-4 w-4 text-[#718096]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a claim, subject, or scope" className="w-full bg-transparent py-3 text-sm outline-none" /></div><button className="rounded-xl bg-[#17212b] px-4 text-sm font-semibold text-white">Search</button><button type="button" onClick={() => void load()} className="rounded-xl border border-[#d9d3c8] bg-[#fffcf7] px-3"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /></button></form><section className="mt-6 space-y-3">{!loading && memories.length === 0 && <p className="rounded-2xl border border-dashed border-[#d9d3c8] bg-[#fffcf7] p-6 text-sm text-[#637080]">No source-backed memory exists in this organization yet.</p>}{memories.map((memory) => <article key={memory.memory_id} className="rounded-2xl border border-[#d9d3c8] bg-[#fffcf7] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[0.14em] text-[#718096]">{memory.subject} · {memory.predicate}</p><h2 className="mt-2 text-lg font-semibold">{memory.claim}</h2></div><span className={`rounded-full border px-2 py-1 text-[10px] font-bold uppercase ${memory.status === "superseded" ? "border-amber-200 bg-amber-50 text-amber-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{memory.status}</span></div><div className="mt-4 grid gap-3 text-xs text-[#637080] sm:grid-cols-3"><p>Scope: {memory.scope}</p><p>Source links: {memory.source_ingestion_ids.length}</p><p>{memory.qwen_generated ? "Qwen-compiled candidate" : "Evidence-only fallback"}</p></div>{(memory.supersedes.length > 0 || memory.superseded_by) && <p className="mt-4 flex items-center gap-2 rounded-xl border border-[#e7dfcf] bg-[#faf7f0] px-3 py-2 text-xs text-[#67593f]"><GitBranch className="h-4 w-4" />{memory.supersedes.length > 0 ? `Supersedes ${memory.supersedes.length} prior claim(s).` : `Superseded by ${memory.superseded_by}.`}</p>}</article>)}</section></div>
}
