import { useCallback, useEffect, useState } from "react"
import { RefreshCw, ShieldCheck } from "lucide-react"
import { getSourceEvents, getWorkflowRuns, type SourceEvent } from "../lib/api"
import type { WorkflowRun } from "../types/schema"

export default function Operations() {
  const [events, setEvents] = useState<SourceEvent[]>([])
  const [runs, setRuns] = useState<WorkflowRun[]>([])
  const [loading, setLoading] = useState(true)
  const refresh = useCallback(async () => { setLoading(true); try { const [source, workflows] = await Promise.all([getSourceEvents(), getWorkflowRuns(30)]); setEvents(source.events); setRuns(workflows.runs) } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  return <div className="mx-auto max-w-5xl"><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-[#2f5eeb]">Technical proof</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Decision Audit</h1><p className="mt-2 text-sm leading-6 text-[#637080]">Source arrival, memory compilation, and governed outcomes remain separate records.</p></div><button type="button" onClick={() => void refresh()} className="inline-flex items-center gap-2 rounded-xl border border-[#d9d3c8] bg-[#fffcf7] px-3 py-2 text-sm font-semibold"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button></div><div className="mt-7 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-[#d9d3c8] bg-[#fffcf7] p-5"><h2 className="font-semibold">Source ingestion</h2><div className="mt-4 space-y-3">{events.length === 0 ? <p className="text-sm text-[#718096]">No source events recorded.</p> : events.map((event) => <div key={event.ingestion_id} className="rounded-xl border border-[#e6e0d5] bg-[#faf7f0] p-3"><p className="text-sm font-semibold">{event.source_name}</p><p className="mt-1 text-xs leading-5 text-[#637080]">{event.excerpt}</p><p className="mt-2 font-mono text-[10px] text-[#8190a0]">{event.stage} · {event.qwen_status}</p></div>)}</div></section><section className="rounded-2xl border border-[#d9d3c8] bg-[#fffcf7] p-5"><h2 className="font-semibold">Workflow decisions</h2><div className="mt-4 space-y-3">{runs.length === 0 ? <p className="text-sm text-[#718096]">No workflow runs recorded.</p> : runs.map((run) => <div key={run.run_id ?? run.id} className="rounded-xl border border-[#e6e0d5] bg-[#faf7f0] p-3"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-[#2f5eeb]" /><p className="text-sm font-semibold">{run.template_id}</p></div><p className="mt-2 text-xs leading-5 text-[#637080]">{run.decision_brief?.recommended_next_action ?? run.brief?.recommended_next_action ?? "No recommendation reported."}</p><p className="mt-2 font-mono text-[10px] text-[#8190a0]">{String(run.decision_brief?.verdict ?? run.brief?.verdict ?? run.status).replaceAll("_", " ")}</p></div>)}</div></section></div></div>
}
