"""Engineering agent: reviews PRs with a brain pre-flight intercept."""

from __future__ import annotations

import logging
import uuid
from typing import Any

from backend.agents.base import AgentRunResult, MCPToolLoopAgent
from backend.config import settings
from backend.core import propagator
from backend.core.schema import DecisionCheckRequest, InterceptResult

logger = logging.getLogger(__name__)

_SYSTEM_PROMPT = """You are the Engineering Agent for Company Brain demo.

You review proposed PR changes. Your job:
  1. A deterministic pre-flight check has already run before you see the PR.
     It is authoritative: do not repeat it or replace it with a text-only
     check. The live metadata is more reliable than any stale number in a
     free-text PR description.
  2. If it says PRE-FLIGHT AUTO-EXECUTE, reply with the verdict
     AUTO-EXECUTE, explicitly say the SAG path is active (not suspended), and
     identify the matched skill_id. You may state the recommended action, but
     do not label this result BLOCK, REVISE, or unsafe.
  3. If it says PRE-FLIGHT SAG SUSPENSION or PRE-FLIGHT INTERCEPT, do not
     approve the PR as-is and recommend the stated alternative.
  4. Reply with the verdict, concise reasoning, and the skill_id that informed
     the call.
"""


class EngineeringAgent(MCPToolLoopAgent):
    agent_id = "engineering-agent-1"
    agent_type = "engineering"
    system_prompt = _SYSTEM_PROMPT

    def tool_schemas(self) -> list[dict[str, Any]]:
        """The deterministic pre-flight owns the engineering demo result.

        A second text-only lookup can contradict the UI's live SAG metadata;
        a model-created compile would also pollute the clean recording org.
        The final response is still generated by real Qwen, with the already
        computed pre-flight context as its source of truth.
        """
        return []


_singleton: EngineeringAgent | None = None


def get_agent() -> EngineeringAgent:
    global _singleton
    if _singleton is None:
        _singleton = EngineeringAgent()
    return _singleton


async def _pre_flight(
    user_message: str,
    agent_id: str,
    metadata: dict[str, Any] | None = None,
    org_id: str | None = None,
) -> tuple[str, bool, str | None, InterceptResult | None]:
    """Run check_intercept against the brain BEFORE the LLM call.

    Returns (augmented_message, intercepted, matched_skill_id, result).
    """
    from backend.core.interceptor import check_decision  # local import avoids cycle

    req = DecisionCheckRequest(
        agent_id=agent_id,
        decision_text=user_message,
        domain="engineering",
        metadata=metadata or {},
        org_id=org_id or settings.DEMO_ORG_ID,
    )
    resp = await check_decision(req)

    if resp.result == InterceptResult.CLEAR or resp.matched_skill is None:
        return user_message, False, None, None

    await propagator.broadcast_intercept(
        agent_id=agent_id,
        skill=resp.matched_skill,
        result=resp.result,
        confidence=resp.confidence,
    )

    if resp.result == InterceptResult.suspended:
        augmented = (
            f"PRE-FLIGHT SAG SUSPENSION from Company Brain:\n"
            f"  result: suspended\n"
            f"  matched skill: {resp.matched_skill.skill_id} ({resp.matched_skill.name})\n"
            f"  suspension_reason: {resp.suspension_reason}\n"
            f"  evidence: {resp.suspension_evidence}\n\n"
            f"Original PR description:\n{user_message}"
        )
    elif resp.result == InterceptResult.AUTO_EXECUTE:
        augmented = (
            f"PRE-FLIGHT AUTO-EXECUTE from Company Brain:\n"
            f"  result: auto_execute (active)\n"
            f"  matched skill: {resp.matched_skill.skill_id} ({resp.matched_skill.name})\n"
            f"  live config passed the SAG applicability gate\n"
            f"  recommended_action: {resp.recommended_action}\n\n"
            "Authoritative review scope:\n"
            "  Review the export configuration change using the live metadata above.\n"
            "  Do not infer a conflicting chunk size from any stale free-text wording.\n"
        )
        return augmented, False, resp.matched_skill.skill_id, resp.result
    else:
        augmented = (
            f"PRE-FLIGHT INTERCEPT from Company Brain:\n"
            f"  result: {resp.result.value}\n"
            f"  matched skill: {resp.matched_skill.skill_id} ({resp.matched_skill.name})\n"
            f"  confidence: {resp.confidence:.2f}\n"
            f"  intercept_message: {resp.intercept_message}\n"
            f"  recommended_action: {resp.recommended_action}\n\n"
            f"Original PR description:\n{user_message}"
        )
    return augmented, True, resp.matched_skill.skill_id, resp.result


async def run(
    user_message: str,
    metadata: dict[str, Any] | None = None,
    org_id: str | None = None,
) -> AgentRunResult:
    agent = get_agent()
    resolved_org = org_id or settings.DEMO_ORG_ID
    pr_id = (metadata or {}).get("pr_id") or f"pr-{uuid.uuid4().hex[:8]}"

    augmented, pre_intercepted, pre_skill, pre_result = await _pre_flight(
        user_message,
        agent.agent_id,
        metadata=metadata,
        org_id=resolved_org,
    )

    await propagator.broadcast_agent_action(
        agent_id=agent.agent_id,
        action_type="pr_received",
        content=user_message[:200],
        metadata={"pr_id": pr_id, "pre_intercepted": pre_intercepted, "pre_skill": pre_skill},
        org_id=resolved_org,
    )

    result = await agent.run(augmented, org_id=resolved_org)

    if pre_intercepted:
        result.intercepted = True
        if not result.intercept_skill:
            result.intercept_skill = pre_skill
    elif pre_result == InterceptResult.AUTO_EXECUTE and pre_skill:
        # Keep the UI proof anchored to the deterministic SAG result even if
        # the model focuses its prose on the implementation recommendation.
        result.response = (
            f"AUTO-EXECUTE PRE-FLIGHT (active): {pre_skill}. "
            "The live config passed the Semantic Applicability Gate.\n\n"
            f"{result.response}"
        )
        if pre_skill not in result.skills_used:
            result.skills_used.insert(0, pre_skill)

    await propagator.broadcast_agent_action(
        agent_id=agent.agent_id,
        action_type="pr_reviewed",
        content=result.response[:200],
        metadata={
            "pr_id": pr_id,
            "skills_used": result.skills_used,
            "intercepted": result.intercepted,
            "intercept_skill": result.intercept_skill,
        },
        org_id=resolved_org,
    )
    return result


__all__ = ["run", "get_agent"]
